### PR TITLE
Add Terser to Build Process 

### PR DESCRIPTION
**Pull request by s0kil**
Adding [Terser](https://github.com/webpack-contrib/terser-webpack-plugin) to optimize production build reduces size by 5x

### CODE REVIEW

**Comment by notrab** [comment]
This currently provides an issue in Safari, are you able to duplicate?

**Comment by s0kil** [comment]
I'm not able to test on Safari, could you try the latest commit?

**Comment by s0kil** [comment]
Another option is to add this package to NPM and use jsDelivr, which will minify the production files.

**Review by notrab — APPROVED** [review]
Looks good to me with Safari!

**Pull request merged**
